version: '2.1'
# Service for SSP
services:
    # Postgresql container
    ssp-postgresql:
        image: swblr.skidata.net/ssp-postgresql:0.2
        ports:
            - 5432:5432
        volumes:
            - db_data:/var/lib/postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGPASSWORD: postgres
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 30s
            timeout: 30s
            retries: 3
    # RabbitMQ container
    ssp-rabbitmq:
        image: swblr.skidata.net/ssp-rabbitmq:0.2
        ports:
            - 15672:15672
            - 5672:5672
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:15672"]
            interval: 30s
            timeout: 10s
            retries: 5
        environment:
            RABBITMQ_PASS: admin
    # Discovery container
    ssp-discovery:
        image: swblr.skidata.net/ssp-discovery
        mem_limit: 1024m
        ports:
            - 8761:8761
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8761"]
            interval: 30s
            timeout: 10s
            retries: 5
        environment:
            SPRING_PROFILES_ACTIVE: docker
            JAVA_OPTS: "-Xmx512m -Xss256k"
    # Auth container
    ssp-auth:
        image: swblr.skidata.net/ssp-auth
        mem_limit: 1024m
        ports:
            - 9999:9999
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9999/auth"]
            interval: 30s
            timeout: 10s
            retries: 5
        depends_on:
            ssp-postgresql:
                condition: service_healthy
            ssp-rabbitmq:
                condition: service_healthy
            ssp-discovery:
              condition: service_healthy
        links:
            - ssp-postgresql:ssp-postgresql
            - ssp-rabbitmq:ssp-rabbitmq
            - ssp-discovery:ssp-discovery
        environment:
            SPRING_PROFILES_ACTIVE: docker
            JAVA_OPTS: "-Xmx512m -Xss256k"
            VIRTUAL_HOST: "*/auth, */auth/*"
    # Product container
    ssp-pim:
        image: swblr.skidata.net/ssp-pim
        mem_limit: 1024m
        ports:
            - 31020:31020
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:31020/info"]
            interval: 30s
            timeout: 10s
            retries: 5
        depends_on:
            ssp-postgresql:
                condition: service_healthy
            ssp-rabbitmq:
                condition: service_healthy
            ssp-discovery:
                condition: service_healthy
        links:
            - ssp-auth:ssp-auth
            - ssp-rabbitmq:ssp-rabbitmq
            - ssp-discovery:ssp-discovery
        environment:
            SPRING_PROFILES_ACTIVE: docker
            JAVA_OPTS: "-Xmx512m -Xss256k"
    # Gateway container
    ssp-gateway:
        image: swblr.skidata.net/ssp-gateway
        mem_limit: 1024m
        ports:
            - 8080:8080
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/info"]
            interval: 30s
            timeout: 10s
            retries: 5
        depends_on:
            ssp-discovery:
                condition: service_healthy
        links:
            - ssp-discovery:ssp-discovery
            - ssp-auth:ssp-auth
            - ssp-pim:ssp-pim
            - ssp-partner:ssp-partner
            - ssp-notification:ssp-notification
        environment:
            SPRING_PROFILES_ACTIVE: docker
            JAVA_OPTS: "-Xmx512m -Xss256k"
            VIRTUAL_HOST: "*/*"
    # Portal container
    ssp-portal:
        image: swblr.skidata.net/ssp-portal
        mem_limit: 1024m
        ports:
            - 10000:10000
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:10000/portal"]
            interval: 30s
            timeout: 10s
            retries: 5
        depends_on:
            ssp-discovery:
                condition: service_healthy
        links:
            - ssp-discovery:ssp-discovery
            - ssp-gateway:ssp-gateway
            - ssp-auth:ssp-auth
        environment:
            SPRING_PROFILES_ACTIVE: docker
            HOST_IP: "$DOCKER_IP"
            SSP_HOSTNAME: "$SSP_HOSTNAME"
            JAVA_OPTS: "-Xmx512m -Xss256k"
            VIRTUAL_HOST: "*/portal, */portal/*"
    #Partner container
    ssp-partner:
        image: swblr.skidata.net/ssp-partner
        mem_limit: 1024m
        ports:
            - 31010:31010
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:31010/info"]
            interval: 30s
            timeout: 10s
            retries: 5
        depends_on:
            ssp-postgresql:
                condition: service_healthy
            ssp-rabbitmq:
                condition: service_healthy
            ssp-discovery:
              condition: service_healthy
        links:
            - ssp-discovery:ssp-discovery
            - ssp-rabbitmq:ssp-rabbitmq
            - ssp-auth:ssp-auth
        environment:
            SPRING_PROFILES_ACTIVE: docker
            JAVA_OPTS: "-Xmx512m -Xss256k"
    #Notification container
    ssp-notification:
        image: swblr.skidata.net/ssp-notification
        mem_limit: 1024m
        ports:
            - 30020:30020
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:30020/info"]
            interval: 30s
            timeout: 10s
            retries: 5
        depends_on:
            ssp-postgresql:
                condition: service_healthy
            ssp-rabbitmq:
                condition: service_healthy
            ssp-discovery:
                condition: service_healthy
        links:
            - ssp-discovery:ssp-discovery
            - ssp-rabbitmq:ssp-rabbitmq
            - ssp-auth:ssp-auth
        environment:
            SPRING_PROFILES_ACTIVE: docker
            JAVA_OPTS: "-Xmx512m -Xss256k"
    #Vault-Container
    ssp-vault:
        image: swblr.skidata.net/ssp-vault
        mem_limit: 1024m
        ports:
            - 30010:30010
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:30010/info"]
            interval: 30s
            timeout: 10s
            retries: 5
        depends_on:
            ssp-postgresql:
                condition: service_healthy
            ssp-rabbitmq:
                condition: service_healthy
            ssp-discovery:
              condition: service_healthy
        links:
            - ssp-discovery:ssp-discovery
            - ssp-rabbitmq:ssp-rabbitmq
            - ssp-auth:ssp-auth
            - ssp-postgresql:ssp-postgresql
        environment:
            SPRING_PROFILES_ACTIVE: docker
            JAVA_OPTS: "-Xmx512m -Xss256k"
    #Dta-Adapter
    ssp-dta-adapter:
        image: swblr.skidata.net/ssp-dta-adapter
        mem_limit: 1024m
        ports:
            - 40010:40010
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:40010/info"]
            interval: 30s
            timeout: 10s
            retries: 5
        depends_on:
            ssp-postgresql:
                condition: service_healthy
            ssp-rabbitmq:
                condition: service_healthy
            ssp-discovery:
                condition: service_healthy
        links:
            - ssp-discovery:ssp-discovery
            - ssp-rabbitmq:ssp-rabbitmq
            - ssp-postgresql:ssp-postgresql
        environment:
            SPRING_PROFILES_ACTIVE: docker
            JAVA_OPTS: "-Xmx512m -Xss256k"
    #Admin Portal container
    ssp-vsm-admin:
        image: swblr.skidata.net/ssp-vsm-admin
        mem_limit: 1024m
        ports:
            - 20000:20000
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:20000/ssp-vsm-admin"]
            interval: 30s
            timeout: 10s
            retries: 5
        depends_on:
            ssp-discovery:
                condition: service_healthy
        links:
            - ssp-discovery:ssp-discovery
            - ssp-gateway:ssp-gateway
            - ssp-auth:ssp-auth
        environment:
            SPRING_PROFILES_ACTIVE: docker
            HOST_IP: "$DOCKER_IP"
            SSP_HOSTNAME: "$SSP_HOSTNAME"
            JAVA_OPTS: "-Xmx512m -Xss256k"
            VIRTUAL_HOST: "*/admin, */admin/*"
    # Order container
    ssp-order:
        image: swblr.skidata.net/ssp-order
        mem_limit: 1024m
        ports:
            - 32010:32010
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:32010/info"]
            interval: 30s
            timeout: 10s
            retries: 5
        depends_on:
            ssp-postgresql:
                condition: service_healthy
            ssp-rabbitmq:
                condition: service_healthy
            ssp-discovery:
                condition: service_healthy
        links:
            - ssp-discovery:ssp-discovery
            - ssp-gateway:ssp-gateway
            - ssp-auth:ssp-auth
            - ssp-partner:ssp-partner
            - ssp-pim:ssp-pim
        environment:
            SPRING_PROFILES_ACTIVE: docker
            JAVA_OPTS: "-Xmx512m -Xss256k"
    #Payment container
    ssp-payment:
        image: swblr.skidata.net/ssp-payment
        mem_limit: 1024m
        ports:
            - 32020:32020
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:32020/info"]
            interval: 30s
            timeout: 10s
            retries: 5
        depends_on:
            ssp-postgresql:
                condition: service_healthy
            ssp-rabbitmq:
                condition: service_healthy
            ssp-discovery:
                  condition: service_healthy
        links:
            - ssp-discovery:ssp-discovery
            - ssp-gateway:ssp-gateway
            - ssp-auth:ssp-auth
        environment:
            SPRING_PROFILES_ACTIVE: docker
            HOST_IP: "$DOCKER_IP"
            SSP_HOSTNAME: "$SSP_HOSTNAME"
            JAVA_OPTS: "-Xmx512m -Xss256k"
    # HA Proxy
    ssp-haproxy:
        image: dockercloud/haproxy
        mem_limit: 512m
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 80:80
            - 443:443
        links:
            - ssp-gateway:ssp-gateway
            - ssp-auth:ssp-auth
            - ssp-portal:ssp-portal
            - ssp-vsm-admin:ssp-vsm-admin
# Persistent volumes for SSP
volumes:
  db_data:
