.catalog:
  name: "Consul"
  description: "Secure Consul cluster"
  version: "0.6-rancher1"
  uuid: consul-0
  questions:
    - variable: ca_crt
      label: "CA certificate"
      type: "multiline"
      required: true
    - variable: consul1_key
      label: "First consul key"
      type: "multiline"
      required: true
    - variable: consul1_crt
      label: "First consul certificate"
      type: "multiline"
      required: true
    - variable: consul2_key
      label: "Second consul key"
      type: "multiline"
      required: true
    - variable: consul2_crt
      label: "Second consul certificate"
      type: "multiline"
      required: true
    - variable: consul3_key
      label: "Third consul key"
      type: "multiline"
      required: true
    - variable: consul3_crt
      label: "Third consul certificate"
      type: "multiline"
      required: true
    - variable: gossip_key
      label: "Communication gossip key"
      type: "multiline"
      required: true
ssp-haproxy:
  scale: 1
ssp-postgres:
  scale: 1
ssp-rabbitmq:
  scale: 1
ssp-discovery:
  scale: 1
ssp-vault:
  scale: 1
ssp-notification:
  scale: 1
ssp-partner:
  scale: 1
ssp-auth:
  scale: 1
ssp-pim:
  scale: 1
ssp-order:
  scale: 1
ssp-payment:
  scale: 1
ssp-dta-adapter:
  scale: 1
ssp-portal:
  scale: 1
ssp-business-portal:
  scale: 1
ssp-vsm-admin:
  scale: 1
