version: '1'
catalog:
  name: "SSP Production"
  version: "1.0-sspprod"
  description: "SSP Production Cluster"
ssp-haproxy:
  scale: 1
ssp-postgres:
  scale: 1
ssp-rabbitmq:
  scale: 1
ssp-discovery:
  scale: 1
ssp-vault:
  scale: 1
ssp-notification:
  scale: 1
ssp-partner:
  scale: 1
ssp-auth:
  scale: 1
ssp-pim:
  scale: 1
ssp-order:
  scale: 1
ssp-payment:
  scale: 1
ssp-dta-adapter:
  scale: 1
ssp-portal:
  scale: 1
ssp-business-portal:
  scale: 1
ssp-vsm-admin:
  scale: 1
